export const UI_CONSTANTS = {
  SECTION_TITLE_CLASS: 'text-3xl mb-4',
  BLOG_SECTION_TITLE: 'Blog',
  CARD_CLASS: 'card',
  BLOG_TITLE_CLASS: 'text-2xl mb-2',
  BLOG_DATE_CLASS: 'text-sm text-gray-400 mb-2',
  BLOG_DESCRIPTION_CLASS: 'mb-2',
  BLOG_LINK_CLASS: 'text-blue-500 hover:underline',
  READ_MORE_TEXT: 'Read More',
  NO_POSTS_MESSAGE_CLASS: 'mb-4',
  NO_POSTS_MESSAGE: 'No blog posts available at the moment.',
  FOLLOW_MESSAGE_CLASS: 'mb-4',
  FOLLOW_MESSAGE: 'Please follow me on Medium for future updates!',
  FOLLOW_BUTTON_CLASS: 'bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out',
  FOLLOW_BUTTON_TEXT: 'Follow on Medium',
  DRAGGABLE_Z_INDEX: 250,
  TITLE_Z_INDEX: 300,
  POPUP_Z_INDEX: 1000,
};